name: Repo Sync

on: push

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: repo-sync/github-sync@v2
      name: Sync repository to branch
      with:
        source_repo: "shrivastava-prateek/shrivastava-prateek"
        source_branch: "master"
        destination_branch: "https://github.com/shrivastava-prateek/shrivastava-prateek.github.io.git"
        github_token: ${{ secrets.GITHUB_TOKEN }}